### ISSUE TITLE
error when start

### ISSUE THREAD

**Issue by ostes** [GoVanguard/legion#105]
appear this errorn when start a legion sh

Strap yourself in, we're starting Legion...
chmod: cannot access './scripts/*.py': No such file or directory
chmod: cannot access './scripts/*.pl': No such file or directory
chmod: cannot access './scripts/*.rb': No such file or directory
Python 3 bin is python3 (/usr/bin/python3)
Pip 3 bin is pip3 (/usr/bin/pip3)
Detected Kali 2019 
Traceback (most recent call last):
  File "legion.py", line 52, in <module>
    from app.logic import *
  File "/root/legion/app/logic.py", line 22, in <module>
    from pyShodan import PyShodan
ModuleNotFoundError: No module named 'pyShodan'

**Comment by sscottgvit** [comment]
Did you clone or grab a release?
How did you start Legion? Was it from the legion directory or from another path? It's very important to be in the path that contains startLegion.sh for it to bootstrap correctly.

**Comment by ostes** [comment]
I install from clone 
I start a legion from root@kali:~# cd /legion
ls 
app              debian            legion.py     README.md         ui
backup           deps              LICENSE       requirements.txt  utilities
CHANGELOG.txt    docker            log           scripts           utilities.py
CONTRIBUTING.md  images            parsers       startLegion.sh    wordlists
controller       legion.conf       plugins       test.py
db               legion.conf.orig  precommit.sh  tmp

**Comment by vsegdacocacola** [comment]
@ostes same issue in 0.3.5. rolled back to 0.3.4 and it works now.
@sscottgvit for some reason I am receiving warning from screnshooter on 0.3.4, that screenshot was not found under ./tmp though.

**Comment by ostes** [comment]
I.m  rolled back 3.4  same error !! and install a new version 3.5 same error too

**Comment by c0rpse7777** [comment]
same issue on start from 1 topic

**Comment by drilus** [comment]
pip3 install shodan
pip3 install pyshodan

**Comment by c0rpse7777** [comment]
Yeah after **pip3 install pyShodan** not error on start.
To fix `chmod: cannot access`  in startLegion.sh I changed this:
```
chmod a+x ./deps/*.sh
chmod a+x ./scripts/*.sh
chmod a+x ./scripts/*.py
chmod a+x ./scripts/*.pl
chmod a+x ./scripts/*.rb
```

to this:
```
chmod a+x ./deps -R
chmod a+x ./scripts -R
```

**Comment by ricken83** [comment]
I'm having the same issue as 1. when trying to install on Parrot 4.6.
Clone
cd legion/
sudo chmod +x startLegion.sh
sudo ./startLegion.sh

Installed shodan and pyshodan.
Now getting issue: 
File "legion.py", line 52, in <module>
 from app.logic import *
File "/home/USER/legion/app/app/logic.py", line 22, in <module>
 from pyShodan import PyShodan
ModuleNotFOundError: No module amed 'pyShodan'

**Comment by mdktch** [comment]
I am facing the same error, any fix? pip list the pyshodan and when tried manually importing it works..

**Comment by jchoy14** [comment]
> I'm having the same issue as 1. when trying to install on Parrot 4.6.
> Clone
> cd legion/
> sudo chmod +x startLegion.sh
> sudo ./startLegion.sh
> 
> Installed shodan and pyshodan.
> Now getting issue:
> File "legion.py", line 52, in 
> from app.logic import *
> File "/home/USER/legion/app/app/logic.py", line 22, in 
> from pyShodan import PyShodan
> ModuleNotFOundError: No module amed 'pyShodan'

> I am facing the same error, any fix? pip list the pyshodan and when tried manually importing it works..

Just to be sure, have you guys installed pyShodan using pip3 so that it's in the Python 3 environment?

**Comment by sscottgvit** [comment]
Code base has been updated to ensure pyShodan gets installed. Please rm -Rf legion and reclone. Let me know if you run into issues.
