### ISSUE TITLE
(Kali) - Docker script doesn't start

### ISSUE THREAD

**Issue by fr0stedfl4ke** [GoVanguard/legion#113]
I'm getting an error after downloading a fresh image.

Using default tag: latest
latest: Pulling from gvit/legion
Digest: sha256:acd7010f5fb257b896d177f09666d4530c388a0f05693e804dd5bcb81e7b82d1
Status: Image is up to date for gvit/legion:latest
standard_init_linux.go:207: exec user process caused "exec format error"

Any assistance would be greatly appreciated.

Thank you

**Comment by jchoy14** [comment]
Out of curiosity, are you using an ARM device?

**Comment by fr0stedfl4ke** [comment]
I'm not, I'm using Kali Linux on a VM with Docker 18.09.1 build 4c52b90

**Comment by sscottgvit** [comment]
Hum, I can't reproduce so far. What version of Kali? I'll build a fresh VM of that version and try again.

**Comment by fr0stedfl4ke** [comment]
32-bit Kali Linux Rolling 2019.2 Using a NON PAE kernel

**Comment by sscottgvit** [comment]
The docker image contains 64-bit elfs, it probably isn't going to run on a 32-bit installation.

**Comment by fr0stedfl4ke** [comment]
Ah, that makes sense. I'll test it out on a 64-bit install and validate its functionality. Thanks for you help.

**Comment by sscottgvit** [comment]
NP man. Good luck! :)
