### ISSUE TITLE
xvfb screenshots not working in kali 2019

### ISSUE THREAD

**Issue by chris948** [GoVanguard/legion#135]
xvfb isn't installed by default. Screenshots show up as blank. I know kali isn't the preferred method, but I appreciate the work you do to support it, I'm already spinning up a kali VM, I don't really want to start a container too for pentesting. 

edit:n/m, I see the file in installDeps. I will debug some more. Sorry.

**Comment by g33k247** [comment]
Was there a fix for the screenshots on native Linux?

**Comment by sscottgvit** [comment]
Evening,

There was a handful of fixes around this that should be showing up once v0.3.7 is packaged and pushed out in kali.
