### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by halfluke** [GoVanguard/legion#143]
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Latest kali, using docker, trying to launch runIt.sh as root.

**Comment by xpelican** [comment]
I have the exact same error on Ubuntu 18.04 and couldn't figure out a solution. Please advise.

**Comment by deikl** [comment]
i have the exact same error on an fresh installed kali linux 2019.4 and couldn´t figure out a solution as well

**Comment by arschlochnop** [comment]
i have the exact same error on an fresh installed kali linux 2020.1.
5.3.0-kali2-amd64

**Comment by skluthe** [comment]
Running into this as well on the latest parrotos version. Think it's an issue with the docker image. It would be a good idea to enable us to download previous versions of the docker image just incase the new one breaks things. Next newest one available on docker hub is 5 months old.

**Comment by sscottgvit** [comment]
We're working on resolving this right now. Additionally, we're going to rerelease each previous image build for users that want to pull a specific version.

**Comment by xpelican** [comment]
@sscottgvit You guys are amazing - I will roll the sleeves to (hopefully) help you out with this as soon as I have some time to do so. Thank you so much.

**Comment by sscottgvit** [comment]
We've just pushed an updated image. Re-clone and give it a try. Initial reports are that the docker image is working on Ubuntu 18.04, Kali 2019 and Ubuntu 18.04 on WSL.

**Comment by skluthe** [comment]
> We've just pushed an updated image. Re-clone and give it a try. Initial reports are that the docker image is working on Ubuntu 18.04, Kali 2019 and Ubuntu 18.04 on WSL.

On parrot os I'm having issues with 
`qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 1841, resource id: 1200, major code: 130 (Unknown), minor code: 3`
Window looks like this:
![image](https://user-images.githubusercontent.com/23664304/73898414-1e323300-483e-11ea-9520-6fec836bc0cf.png)
I believe it's related to this issue.

**Comment by sscottgvit** [comment]
We've published some changes that have resolved some edge cases for docker. Mind giving 0.3.7 a try?

**Comment by sscottgvit** [comment]
This should be fixed. Closing for now.
