### ISSUE TITLE
pyfiglet.FontNotFound: starwars

### ISSUE THREAD

**Issue by jchoy14** [GoVanguard/legion#161]
Potential issue when running legion on some Kali environments including but not limited to WSL.

**Comment by sampl3x** [comment]
How to resole this error when running legion?
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 147, in preloadFont
    raise FontNotFound(font)
pyfiglet.FontNotFound: starwars

**Comment by jchoy14** [comment]
The repo will be updated soon with the fix, but the fix is to just install pyfiglet==0.8.post1

**Comment by carhackpils** [comment]
also you can just comment this line in legion.py:
`cprint(figlet_format('LEGION', font='starwars'), 'yellow', 'on_red', attrs=['bold'])`

**Comment by MidnightSeer** [comment]
still an issue, but the commenting out the line fixed it.
