### ISSUE TITLE
Importing Nmap scans crashes the application

### ISSUE THREAD

**Issue by AmbitiousOkie** [GoVanguard/legion#166]
This is similar to the last posted issue, but version 0.3.5, 0.3.6a, 0.3.6b all consistently crash when importing Nmap XML files.

**Comment by AmbitiousOkie** [comment]
I haven't tested older than 0.3.5.

**Comment by oldkingcone** [comment]
this happens still, and its frustrating because all scan information is lost.

```
QWidget::repaint: Recurisive repaint detected
QBackingStore::endPait() called with active painter; did you forget to destroy it or call QPainter::end() on it?
```
Is the only error message displayed, there is no crash report. Nothing.

**Comment by sscottgvit** [comment]
What platform and installation method did you experience the problem under?

**Comment by oldkingcone** [comment]
Kali linux vm. 
Legion Version: 0.3.6-1580902879

**Comment by gracjanj** [comment]
Please add to the project's readme that it is in early development and should be used with caution. Legion is unstable, broken, neglected and there's a high risk of losing information during the assessment. Sparta still works great.

**Comment by sscottgvit** [comment]
This was related to sqlalchemy session handling. Fixed.
