### ISSUE TITLE
Config file with modifications is overwritten with defaults

### ISSUE THREAD

**Issue by mcjon3z** [GoVanguard/legion#167]
A modified configuration file is overwritten with defaults upon closing the application if an nmap scan is run during a session. To duplicate:

- Modify config file (e.g. just add a test comment line "###TEST" to top of the config)
- Open the application and close it
- Check config file - modification is present
- Run staged nmap scan
- Close the application - note that a logger entry "Settings have been changed" is logged
- Reopen the application and check config file - the ###TEST comment should be missing

This was tested on install from Parrot repo as well as from a clone of the current branch, running both as a standard user and as root.

**Comment by ohSaucy** [comment]
@mcjon3z We're having difficulty replicating this on the current version. Are you still experiencing this problem in the latest version? Any additional details about your usage or environment would be helpful in the event that it is still an issue.

**Comment by mcjon3z** [comment]
Honestly I have not tried recently but will try to test and get back to you. When you say most recent version does that include the most recent version pushed to the kali repos or only master branch on github?

**Comment by ohSaucy** [comment]
Whichever of those environments you have available to update (using apt-get update legion or the github repo) will be fine. The Kali repo has been updated recently.

**Comment by mcjon3z** [comment]
I'm not able to duplicate this anymore using the repo version in Kali so I'm going to go ahead and close the issue. I'll let you know if I stumble across it again...thanks!
