### ISSUE TITLE
Different Nmap parameters in Legion than in Sparta

### ISSUE THREAD

**Issue by Ferrariman1996** [GoVanguard/legion#168]
Greating,

when I was using Sparta 1.0.4 (Kali 2019.3 and 2019.4) and Legion 0.3.6 (Kali 2020.1) for my Master's thesis. I was testing these apps against a honeypot and I came accoss a difference in the software information. In Sparta one of the honeypot services, specificaly Dionaea's MS-SQL, was detected as the honeypot, but in Legion, it was detected as a normal Microsoft SQL server, no information about the honeypot.

I was able to find out that Sparta and Legion use different Nmap parameters:
*  Sparta Nmap command (simplified): `nmap -T4 -sV -n -sSU -O -p T:1433 <IP>`
*  Legion Nmap command on Easy settigns (simplified): `nmap  -T4 -sC -n -sT -p T:1433 <IP>`

May I ask what is the reason in this difference?

Thank you for your answer, it would be very usefull for my thesis.

**Comment by jchoy14** [comment]
-sV is also included in the add hosts screen when the scan is set to Hard. That's for version detection. -sC is equivalent to --script=default. Basically we wanted Easy settings to run a simpler, quicker scan and not run any particular nmap scripts. The issue with version detection is related to how the data is processed, once we have some more time we will troubleshoot it.

**Comment by Ferrariman1996** [comment]
Thank you for your answer and information.
