### ISSUE TITLE
'getTimestamp' is not defined 

### ISSUE THREAD

**Issue by securesean** [GoVanguard/legion#179]
I get a crash on this line:
https://github.com/GoVanguard/legion/blob/799b9ce2c5763f2c0ed0295d2c8b74a117472390/ui/view.py#L1651

But I have no idea why because the code clearly has the function name - maybe it's a scope issue?

![image](https://user-images.githubusercontent.com/10591609/82281472-05660d00-9957-11ea-943b-4a45b59fbcc3.png)

Scan data attached. I clicked the brute force tab, selected mysql to brute, selected a text file for from seclists (apt install seclists) usr/share/seclists/Passwords/Default-Credentials/mysql-betterdefaultpasslist.txt

 [legionScanData.zip](https://github.com/GoVanguard/legion/files/4648062/legionScanData.zip)

**Comment by MidnightSeer** [comment]
see #180

**Comment by securesean** [comment]
Do you want me to test that?
