### ISSUE TITLE
brute rdp does not work

### ISSUE THREAD

**Issue by MidnightSeer** [GoVanguard/legion#180]
Replicate:

Send to Brute
select a username file
select a password file
set threads to 1

Error in terminal:
Traceback (most recent call last):
  File "/home/kali/Documents/GitHub/legion/ui/view.py", line 1578, in <lambda>
    bWidget.runButton.clicked.connect(lambda: self.callHydra(bWidget))
  File "/home/kali/Documents/GitHub/legion/ui/view.py", line 1638, in callHydra
    hydraCommand = bWidget.buildHydraCommand(self.controller.getRunningFolder(),
  File "/home/kali/Documents/GitHub/legion/ui/dialogs.py", line 341, in buildHydraCommand
    self.outputfile = runningfolder + "/hydra/" + getTimestamp() + "-" + str(self.ip) + "-" + self.port + "-" + \
NameError: name 'getTimestamp' is not defined

**Comment by MidnightSeer** [comment]
adding this seems to fix it:
from app.timing import getTimestamp
into
/home/kali/Documents/GitHub/legion/ui/dialogs.py

**Comment by matheus-rambo** [comment]
Hi @MidnightSeer , I had the same issue here, and I was going to open a pull request with a fix, than I saw your issue. 

So, could you please open a pull request with this fix?

**Comment by MidnightSeer** [comment]
Done #183
