### ISSUE TITLE
getTimestamp is not defined

### ISSUE THREAD

**Issue by Ayodub** [GoVanguard/legion#194]
Whenever attempting to use Brute Legion will crash and give me this message:

Traceback (most recent call last):
  File "/usr/share/legion/ui/view.py", line 1578, in <lambda>
    bWidget.runButton.clicked.connect(lambda: self.callHydra(bWidget))
  File "/usr/share/legion/ui/view.py", line 1638, in callHydra
    hydraCommand = bWidget.buildHydraCommand(self.controller.getRunningFolder(),
  File "/usr/share/legion/ui/dialogs.py", line 341, in buildHydraCommand
    self.outputfile = runningfolder + "/hydra/" + getTimestamp() + "-" + str(self.ip) + "-" + self.port + "-" + \
NameError: name 'getTimestamp' is not defined
Aborted

I have seen some similar issues to this some months ago, but could not see anything on how to fix it. My Legion is 100% up to date, having just re-downloaded it today.

**Comment by abaddonware** [comment]
Hello

I have the same problem with version 0.3.6-1580 installed with apt-get install legion, when I run a brute

I installed version 0.3.7-1596 of
https://kalilinuxtutorials.com/legion-penetration-testing/

I manage to launch a brute but I have a problem when I launch a scan it does not do the pentest example it does not launch nikto, the scan is incomplete,


 test performed on Kali 2019-3 and 2020-2
Ty

**Comment by sscottgvit** [comment]
@Ayodub Can you post your legion/ui/dialogs.py?
@abaddonware We did intentionally remove nikto from the scheduler as we had people report that for scans encompassing a large number of web hosts it can take an exhaustively long time to complete. Maybe we can add a flag for enabling or disabling scans that behave this way.

**Comment by sscottgvit** [comment]
Bump.

**Comment by ddubson** [comment]
I believe this bug can be closed as it was addressed in this [commit](https://github.com/GoVanguard/legion/commit/f554c732fa30965c222665fd1da2d57386f046e6). 

Please upgrade Legion to the latest patch version.
