### ISSUE TITLE
Can't start legion via an RDP connection to Kali

### ISSUE THREAD

**Issue by tkl-priv** [GoVanguard/legion#201]
I can't start legion via an RDP connection to Kali.
Directly on the machine via webconsole in ESXi it's starting without any error.
Only via RDP it's not starting.
I also tried different RDP clients with the same result ...

I am receiving the following error message:
```
No protocol specified
qt.qpa.xcb: could not connect to display :10.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

zsh: abort      sudo legion
```

Steps to reproduce:
1) Configure xrdp on Kali
2) Connect via RDP to Kali
3) Try to start Legion

I've also tried the version in Kali "0.3.7-0kali2" and also the newest release here from GitHub.

**Comment by aBoyNicholas** [comment]
me too

**Comment by wgknowles** [comment]
add `export XAUTHORITY=~/.Xauthority` to your .bashrc

**Comment by tkl-priv** [comment]
Great, it's working now! Thank you very much 👍
