### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5'

### ISSUE THREAD

**Issue by Jassi2** [GoVanguard/legion#204]
I am on Kali Linux OS.
I get this error when i try to run legion.
**Strap yourself in, we're starting Legion...
Python 3 bin is Missing ()
Pip 3 bin is Missing ()
Detected Kali ? 
Traceback (most recent call last):
  File "/home/jassi/legion/legion.py", line 17, in <module>
    from app.ProjectManager import ProjectManager
  File "/home/jassi/legion/app/ProjectManager.py", line 23, in <module>
    from app.Project import Project, ProjectProperties
  File "/home/jassi/legion/app/Project.py", line 20, in <module>
    from app.auxiliary import Wordlist
  File "/home/jassi/legion/app/auxiliary.py", line 21, in <module>
    from PyQt5 import QtCore, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'**

But i have already installed PyQt5.

**pip3 install PyQt5**                                                                                       
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyQt5 in /home/jassi/.local/lib/python3.9/site-packages (5.15.4)
Requirement already satisfied: PyQt5-Qt5>=5.15 in /home/jassi/.local/lib/python3.9/site-packages (from PyQt5) (5.15.2)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /home/jassi/.local/lib/python3.9/site-packages (from PyQt5) (12.9.0)

**pip install PyQt5**                                                                                          
Requirement already satisfied: PyQt5 in /home/jassi/.local/lib/python3.9/site-packages (5.15.4)
Requirement already satisfied: PyQt5-Qt5>=5.15 in /home/jassi/.local/lib/python3.9/site-packages (from PyQt5) (5.15.2)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /home/jassi/.local/lib/python3.9/site-packages (from PyQt5) (12.9.0)

Also, 
**python --version**
Python 2.7.18

**python3 --version**
Python 3.9.0

**ls /usr/bin/python**
usr/bin/python

**ls /usr/bin/python***
/usr/bin/python     /usr/bin/python3.9         /usr/bin/python3-pasteurize  /usr/bin/python-faraday
/usr/bin/python2    /usr/bin/python3.9-config  /usr/bin/python3-qr
/usr/bin/python2.7  /usr/bin/python3-config    /usr/bin/python3-tor-prompt
/usr/bin/python3    /usr/bin/python3-futurize  /usr/bin/python3-wsdump

**Comment by lmakonem** [comment]
same error here

**Comment by ddubson** [comment]
At the current moment, Legion, when started locally, must run with `sudo` privileges:

```
sudo ./startLegion.sh
```

If you are starting Legion like this, your dependencies must also be fetched with `sudo` privileges before startup. You might need to rerun fetching dependencies again, Legion script does not keep re-running fetch dependencies every time. So try something like this:

```bash
# Upgrade pip installation that python3 manages -- this is important to make sure fetching of dependencies works properly
sudo python3 -m pip install --upgrade pip

# Fetch dependencies with sudo privileges (at root level of repository)
sudo pip3 install -r requirements.txt

# Attempt to start Legion once again if dependencies installed successfully
sudo ./startLegion.sh
```

Hope this helps!

**Comment by stick0ne** [comment]
ERROR: Ignored the following versions that require a different python version: 0.0.3 Requires-Python ==3.6.*; 0.0.4 Requires-Python ==3.6.*
ERROR: Could not find a version that satisfies the requirement PyQt5_sip<4.20,>=4.19.11 (from pyqt5) (from versions: 12.7.0, 12.7.1, 12.7.2, 12.8.0, 12.8.1, 12.9.0, 12.9.1, 12.10.1, 12.11.0)
ERROR: No matching distribution found for PyQt5_sip<4.20,>=4.19.11

**Comment by sscottgvit** [comment]
We've moved to PyQt6 now.
