### ISSUE TITLE
Error Importing Nmap File

### ISSUE THREAD

**Issue by flamecopper** [GoVanguard/legion#215]
Hi there,

I am using legion to do ftp-anon scan,
It show error importing xml malform package something like that.
What should I do?

**Comment by sscottgvit** [comment]
@flamecopper Can you reproduce and drop the console output?

**Comment by sscottgvit** [comment]
Likely the xml was corrupted or part of the schema was unsupported. Upload the problem xml from nmap and I can diagnose. Closing until then.
