### ISSUE TITLE
Segmentation Fault when running scripts on legion

### ISSUE THREAD

**Issue by flamecopper** [GoVanguard/legion#217]
6
0
{"time": "2022-03-04 14:08:21,340", "name": "Queuing: nmap -Pn 172.25.120.240 -p 80 --script=http-headers.nse --script-args=unsafe=1", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "controller", "filename": "controller.py", "line": 673}}
{"time": "2022-03-04 14:08:22,357", "name": "runCommand called for stage 0", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "controller", "filename": "controller.py", "line": 690}}
nmap -Pn 172.25.120.240 -p 80 --script=http-headers.nse --script-args=unsafe=1
{"time": "2022-03-04 14:08:23,694", "name": "Process 2 is done!", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "controller", "filename": "controller.py", "line": 839}}
{"time": "2022-03-04 14:08:23,695", "name": "nmap xml report is likely malformed: [Errno 2] No such file or directory: '/root/.local/share/legion/tmp/legion-kpgvd010-tool-output/httpheadersnse/20220304140820793603-http-headers.nse-172.25.120.240-80.xml'", "level": "ERROR", "data": {"logger_name": "legion"}, "context": {"module": "NmapImporter", "filename": "NmapImporter.py", "line": 76}}
Segmentation fault

**Comment by sscottgvit** [comment]
@flamecopper  Can you reproduce and drop the segfault details found in dmesg?

**Comment by sscottgvit** [comment]
This was likely sqlalchemy. Big upgrades there and should not happen anymore with larger imports. Also be aware of nmap 7.29 which can segfault for no reason.
