### ISSUE TITLE
UpdateProgress Crash?? or Zsh: IOT instruction legion

### ISSUE THREAD

**Issue by benjjyman** [GoVanguard/legion#220]
Running Wizard on a preinstalled image from Kali Downloads:
after initializing a basic scan  the program errors out leaving the screen output included.
What am i doing wrong ?? input into scan field was 192.168.0.0/24 
the program errors out around the 8-10 second mark with maybe 80 seconds left on a basic network scan.

just for clarity going to include extra info:-

Operating System: Kali GNU/Linux Rolling
          Kernel: Linux 5.16.0-kali7-amd64
    Architecture: x86-64
 Hardware Vendor: Dell Inc.
  Hardware Model: Precision M6800
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.2"
VERSION_ID="2022.2"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
                                   
Python 3.10.4

 Screen grab of output:-

{"time": "2022-05-02 00:34:57,353", "name": "Creating temporary project at application start...", "level": "INFO", "data": {"logger_name": "legion-startup"}, "context": {"module": "legion", "filename": "legion.py", "line": 118}}
{"time": "2022-05-02 00:34:57,539", "name": "Wordlist was created/opened: /home/benj/.local/share/legion/tmp/legion-3xbtw6_m-tool-output/legion-usernames.txt", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "auxiliary", "filename": "auxiliary.py", "line": 115}}
{"time": "2022-05-02 00:34:57,540", "name": "Wordlist was created/opened: /home/benj/.local/share/legion/tmp/legion-3xbtw6_m-tool-output/legion-passwords.txt", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "auxiliary", "filename": "auxiliary.py", "line": 115}}
{"time": "2022-05-02 00:34:57,735", "name": "Loading settings file..", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "settings", "filename": "settings.py", "line": 37}}
{"time": "2022-05-02 00:34:57,867", "name": "Legion started successfully.", "level": "INFO", "data": {"logger_name": "legion-startup"}, "context": {"module": "legion", "filename": "legion.py", "line": 137}}
{"time": "2022-05-02 00:35:18,311", "name": "runStagedNmap called for stage 1", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "controller", "filename": "controller.py", "line": 739}}
{"time": "2022-05-02 00:35:18,598", "name": "Queuing: nmap -T4 -sV -sT -p T:80,81,443,4443,8080,8081,8082 192.168.0.14 -oA /home/benj/.local/share/legion/tmp/legion-yxgiweqq-running/nmap/20220502003518312932-nmapstage1", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "controller", "filename": "controller.py", "line": 673}}
{"time": "2022-05-02 00:35:19,505", "name": "runCommand called for stage 1", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "controller", "filename": "controller.py", "line": 690}}
{"time": "2022-05-02 00:35:19,505", "name": "runCommand connected for stage 1", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "controller", "filename": "controller.py", "line": 693}}
nmap -T4 -sV -sT -p T:80,81,443,4443,8080,8081,8082 192.168.0.14 -oA /home/benj/.local/share/legion/tmp/legion-yxgiweqq-running/nmap/20220502003518312932-nmapstage1
{"time": "2022-05-02 00:35:20,485", "name": "Process 1 is done!", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "controller", "filename": "controller.py", "line": 839}}
Processing service result *********** name=http prod= ver= extra= fing=
Did not find service *********** name=http prod= ver= extra= fing=
Traceback (most recent call last):
  File "/usr/share/legion/app/importers/NmapImporter.py", line 184, in run
    self.updateProgressObservable.updateProgress(totalprogress)
  File "/usr/share/legion/app/actions/updateProgress/UpdateProgressObservable.py", line 32, in updateProgress
    observer.onProgressUpdate(progress)
  File "/usr/share/legion/ui/observers/QtUpdateProgressObserver.py", line 33, in onProgressUpdate
    self.progressWidget.setProgress(progress)
  File "/usr/share/legion/ui/ancillaryDialog.py", line 55, in setProgress
    self.progressBar.setValue(progress)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
zsh: IOT instruction  legion

**Comment by gstb989** [comment]
Ran into the same issue, seems like they are pushing everyone towards the docker version.

**Comment by gstb989** [comment]
Delete the instance that comes with Kali and use their install instructions, this fixed my instance. 
https://github.com/GoVanguard/legion#traditional-installation-method

**Comment by benjjyman** [comment]
Thanks

**Comment by dcarlsongvit** [comment]
This issue should be resolved.
