### ISSUE TITLE
please help me i found a little problem with legion tool with QT plugin 

### ISSUE THREAD

**Issue by dragonkali** [GoVanguard/legion#227]
i have screenshot about the problem  

https://user-images.githubusercontent.com/107942173/178204185-d8fd04c7-1e61-4ccc-a069-99ed4cea598c.mp4

 let me explain about in video 
 in this video im using kali linux version 2022.2 im writing legion in root but legion not running and error massage found   
       Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

but i have install QTcreator version 7.0.2-2 in linux  but legion not open gui legion tool     please help me    if you help me im very thank you about your help

**Comment by sscottgvit** [comment]
@dragonkali Try this: Open a new tab and `sudo legion`

I say this because it sort of looks like it cannot connect to X as root in your example.

**Comment by sscottgvit** [comment]
Try with the latest kali package.
