### ISSUE TITLE
All Scans Crashing

### ISSUE THREAD

**Issue by feint9** [GoVanguard/legion#231]
Hi,

Fresh install of Kali, full update.

uname -a       
Linux k9 5.18.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1kali1 (2022-08-31) x86_64 GNU/Linux

legion 0.3.7-1622656779

All the process crash and no ips and ports get added to the console. Some msg from the log file bellow...

https://pastebin.com/KZtF3YS7

**Comment by sscottgvit** [comment]
@numb699 @feint9 Can you try the following?
sudo apt install snapd -y
sudo systemctl enable --now snapd.apparmor
sudo systemctl start snapd
sudo snap install nmap
sudo mv /usr/bin/nmap /usr/bin/nmap-7.92
sudo ln -s /snap/bin/nmap /usr/bin/nmap

Then verify the version with:
nmap -v

It should be version 7.93. If so, try starting legion.

**Comment by numb699** [comment]
Absolutely spot on. Thank you so much!
