### ISSUE TITLE
neverending stage 3

### ISSUE THREAD

**Issue by kubastas** [GoVanguard/legion#242]
The stage 3 scan never ends. Is the stage 3 scan configuration in config file correct? It looks different than others - no port definition.

stage1-ports="PORTS|T:80,81,443,4443,8080,8081,8082"
stage2-ports="PORTS|T:25,135,137,139,445,1433,3306,5432,U:137,161,162,1434"
stage3-ports="NSE|vulners"
stage4-ports="PORTS|T:23,21,22,110,111,2049,3389,8080,U:500,5060"
stage5-ports="PORTS|T:0-20,24,26-79,81-109,112-134,136,138,140-442,444,446-1432,1434-2048,2050-3305,3307-3388,3390-5431,5433-8079,8081-29999"
stage6-ports="PORTS|T:30000-65535"

**Comment by sscottgvit** [comment]
This could be the vulners script was messed up on that system. It certainly does not have this problem now. Keep in mind though, you'll want to do a fresh clone on

**Comment by sscottgvit** [comment]
This could be the vulners script was messed up on that system. It certainly does not have this problem now. Keep in mind though, you'll want to do a fresh clone on a supported platform.
