### ISSUE TITLE
Cannot load legion-aeusldet-tool-output screenshots

### ISSUE THREAD

**Issue by ohSaucy** [GoVanguard/legion#38]
![github](https://user-images.githubusercontent.com/25316719/52497699-be5e6900-2ba4-11e9-99f3-dd6b8a5f746a.png)

Some screenshots throw this alert box and cannot be loaded

**Comment by littleheary** [comment]
i have this problem too,how can  i solve?

**Comment by g33k247** [comment]
Also seeing this issue, plus the screenshots in the source directory are "black".

**Comment by JensTimmerman** [comment]
legion uses cutycapt to create screenshots, so it must be installed on your system

https://github.com/GoVanguard/legion/blob/ef73d905d5e8441728554c3ad2a0537dfa3c0e3b/app/settings.py#L228

to fix this I installed a cutycapt fork that takes bigger screenshots:

https://github.com/oracle/infinity-cutycapt

```
git clone git@github.com:oracle/infinity-cutycapt.git
cd infinity-cutycapt/
qmake-qt5 #might just be qmake on  your system
make
```
This gives you a CutyCapt binary, place it where legion expects it, or edit the settings file to point to this executable

**Comment by sscottgvit** [comment]
This should be resolved.
