### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by strunz983** [GoVanguard/legion#74]
Hi my OS is Linux kali 4.19.0-kali3-amd64 #1 SMP Debian 4.19.20-1kali1 (2019-02-14) x86_64 GNU/Linux
when i start ./startLegion.sh i got this message
./startLegion.sh
Strap yourself in, we're starting Legion...
Detected Kali ? 
Checking for additional Sparta scripts...
/root/stuff/legion
smbenum.sh is already installed
snmpbrute.py is already installed
ms08-067_check.py is already installed
rdp-sec-check.pl is already installed
ndr.py is already installed
installDeps.sh is already installed
snmpcheck.rb is already installed
smtp-user-enum.pl is already installed
{"time": "2019-03-06 22:03:59,849", "name": "Import failed. PyQt4 library not found. If on Ubuntu or similar try: agt-get install python3-pyqt4", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "legion", "filename": "legion.py", "line": 29}}
{"time": "2019-03-06 22:03:59,849", "name": "cannot import name 'QtWidgets'", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "legion", "filename": "legion.py", "line": 30}}

apt-get install python3-pyqt4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pyqt4 is already the newest version (4.12.1+dfsg-2+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

apt-get install python3-pyqt5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pyqt5 is already the newest version (5.11.3+dfsg-1+b3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

pip install PyQt5
Requirement already satisfied: PyQt5 in /usr/local/lib/python3.7/dist-packages (5.11.3)
Requirement already satisfied: PyQt5_sip<4.20,>=4.19.11 in /usr/local/lib/python3.7/dist-packages (from PyQt5) (4.19.14)

i also install and pip install -r requirements.txt and i got same issue

Thank you .

**Comment by sscottgvit** [comment]
That line suggesting the install of PyQt4 should have said PyQt5. We'll get that fixed. I noticed that pip points to python3.7, which isn't yet compatible. Legion will explicitly search for and use python3.6, at least for the moment. Is python3.6 present on the system? I'll look into seeing if we can re-include python3.7 in the scripts after some testing.

**Comment by strunz983** [comment]
i have on my system python -V    Python 2.7.16rc1 and
python3 -V   Python 3.7.2+

**Comment by sscottgvit** [comment]
Looks like it's working well with python 3.7 now. I added in support. Please delete your legion directory and reclone and try again. (If you'd rather do a git pull please touch .justcloned and rm .initialized in the legion directory to force reinitialization). Let me know how it goes.

**Comment by strunz983** [comment]
now is working fine 
Thank you  :)
