### ISSUE TITLE
Error - Legion not starting

### ISSUE THREAD

**Issue by filebe777** [GoVanguard/legion#76]
sudo ./startLegion.sh
Strap yourself in, we're starting Legion...
Python 3 bin is python3 (/usr/bin/python3)
Pip 3 bin is pip3.6 (/usr/local/bin/pip3.6)
Detected Kali 2019 
{"time": "2019-03-07 06:50:00,848", "name": "Import failed. Quamash or asyncio not found.", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "legion", "filename": "legion.py", "line": 37}}
{"time": "2019-03-07 06:50:00,850", "name": "No module named 'quamash'", "level": "INFO", "data": {"logger_name": "legion"}, "context": {"module": "legion", "filename": "legion.py", "line": 38}}

**Comment by sscottgvit** [comment]
Could you try a sudo pip3.6 install -r requirements.txt from the legion directory please?

**Comment by Arrakisconsulting** [comment]
If "**_sudo pip3.6 install -r requirements.txt_**" doesn't work...try "_**sudo pip install -r requirements.txt**_"...you may get different results.

**Comment by filebe777** [comment]
this is the new result i got in kali

root@kali:~/Desktop/legion# sudo pip install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting asyncio==3.4.3 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/da/54/054bafaf2c0fb8473d423743e191fcdf49b2c1fd5e9af3524efbe097bafd/asyncio-3.4.3.tar.gz (204kB)
    100% |████████████████████████████████| 204kB 1.8MB/s 
Collecting aiohttp==3.4.4 (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement aiohttp==3.4.4 (from -r requirements.txt (line 2)) (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.21.4, 0.21.5, 0.21.6, 0.22.0a0, 0.22.0b0, 0.22.0b1, 0.22.0b2, 0.22.0b3, 0.22.0b4, 0.22.0b5, 0.22.0b6, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.22.4, 0.22.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6.post1, 2.0.7, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0a4, 2.3.0, 2.3.1, 2.3.2b2)
No matching distribution found for aiohttp==3.4.4 (from -r requirements.txt (line 2))

**Comment by DefensiveThinking** [comment]
I am getting this same error on ParrotOS.

**Comment by Arrakisconsulting** [comment]
I had the same issue....but did a combination of the following (although forgot what order).  Upgraded Python, created an alias to point python to v3 rather than 2.7, ran pip the way I mentioned above...and I seem to recall that I ran the pip install script to specifically install asyncio just to be sure.   It worked for me after that....I'm also running on Kali.

**Comment by ohSaucy** [comment]
We're working on an update to the installer script to resolve this. Until then, Try installing pip3.7, and then run:
sudo pip3.7 install -r requirements.txt

**Comment by DefensiveThinking** [comment]
I will make sure I keep following to see the next update.

**Comment by sscottgvit** [comment]
We've made some improvements to the dep handelers to try to catch all cases. Give it another go. Also give the docker version a try (see readme for how to). Closing for now.
