### ISSUE TITLE
docker run have problem

### ISSUE THREAD

**Issue by littleheary** [GoVanguard/legion#93]
Using default tag: latest
latest: Pulling from gvit/legion
Digest: sha256:48ccd9811513d778a9e38e607ff4b04b44c6851c876c5dc89bceff1687faeba1
Status: Image is up to date for gvit/legion:latest
Unable to find image 'legion:latest' locally
docker: Error response from daemon: repository legion not found: does not exist or no pull access.
See 'docker run --help'.

**Comment by jchoy14** [comment]
Interesting. What OS/version are you using? I will try to replicate this issue.

**Comment by njfox** [comment]
I'm running into this on Arch Linux. Docker version:

`Docker version 18.09.6-ce, build 481bc77156`

**Comment by c0rpse7777** [comment]
same issue on kali linux latest

**Comment by sscottgvit** [comment]
This is now sorted. There was a typo in the runIt script. That has been resolved. Keep in mind the script usage has changed slightly, so after you do a pull check the readme for that info.
