### ISSUE TITLE
startlegion.sh doesn't install runtimes like nmap and isn't clear that this needs to be done manually

### ISSUE THREAD

**Issue by trelane** [GoVanguard/legion#98]
using vanilla ubuntu, the startlegion.sh script does not properly check for runtimes like hydra, nmap, nikto, mysql-client, ftp, cutycapt, etc.
this should probably be added.

**Comment by sscottgvit** [comment]
This is now sorted out. Each of these will be attempted separately to avoid the possibility of failure on any given one. I would also suggest using the docker version as much as possible. :)
